Feature fds 124 documentation
Sage-Bionetworks/schematic_db pull request #186
Opened 2023-03-23 18:40 UTC by andrewelamb

Fixes [FDS-124](https://sagebionetworks.jira.com/jira/software/c/projects/FDS/issues/FDS-124)

[FDS-124]: https://sagebionetworks.jira.com/browse/FDS-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-23 18:45 UTC, andrewelamb commented
@mialy-defelice @milen-sage @GiaJordan @linglp 
This is a first draft for the readme. This is just intended for devs, and not users. The user section will be added after this. You all are the intended audience, so if you could look this over and tell me where things aren't clear, or if there is anything I should add please let me know.

2023-03-23 22:31 UTC, mialy-defelice requested changes

2023-03-23 22:31 UTC, mialy-defelice commented on README.md
Can you format `tests/data/secrets.yml` and `.gitignore` on line 41 as inline code?

In the secrets section can you specify that the user needs to create a new project and use that new projectId?

2023-03-23 22:39 UTC, mialy-defelice commented on README.md
I also had an issue previously with `synapse client` installation, does the movement of the `all-extras` install address this?

2023-03-24 14:40 UTC, andrewelamb commented on README.md
#183 Should address the installation issue you had earlier. Now you should be able to do 

`poetry install --all-extras`

or 

`poetry install -E synapse`

2023-03-27 15:43 UTC, linglp commented
@andrewelamb Do you think if it will be better to use pre-commit and run linters as pre-commit hook? So that before each commit, the formatting of the code would already be taken care of.

2023-03-27 15:54 UTC, andrewelamb commented
@linglp  Essentially if you don't have MySQL installed locally you can't install the mysql package. (I think the same is true for Postgres) This was the motivation to make it an extra. I should add a section describing this.

2023-03-27 15:59 UTC, andrewelamb commented
@linglp I've been thinking about adding pre-commit hooks since Bruno talked about them at one point. I would have to look into them, and see if they would make sense.

2023-04-05 20:55 UTC, merged